CREATE TABLE LOCATION
(
  ZONE_ID VARCHAR(4) NOT NULL,
  STATE_NAME VARCHAR(20) NOT NULL,
  DISTRICT_NAME VARCHAR(20) NOT NULL,
  PRIMARY KEY (ZONE_ID),
  UNIQUE (DISTRICT_NAME)
);

--ALTER TABLE LOCATION drop UNIQUE (state_name);

SELECT * FROM location;

INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn47', 'tamil_nadu', 'karur');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn01', 'tamil_nadu', 'chennai central');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn02', 'tamil_nadu', 'chennai north west');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn03', 'tamil_nadu', 'chennai north east');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn04', 'tamil_nadu', 'chennai east');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn05', 'tamil_nadu', 'chennai north');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn06', 'tamil_nadu', 'chennai south east');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn07', 'tamil_nadu', 'chennai south');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn09', 'tamil_nadu', 'chennai west');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn10', 'tamil_nadu', 'chennai south west');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn11', 'tamil_nadu', 'tambaram');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn12', 'tamil_nadu', 'poonamalee');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn13', 'tamil_nadu', 'ambattur');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn14', 'tamil_nadu', 'sholinganallur');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn15', 'tamil_nadu', 'ulundurpet');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn16', 'tamil_nadu', 'tindivanam');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn18', 'tamil_nadu', 'red hills');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn19', 'tamil_nadu', 'chengalpattu');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn21', 'tamil_nadu', 'kanchipuram');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn22', 'tamil_nadu', 'meenambakkam');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn23', 'tamil_nadu', 'vellore');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn24', 'tamil_nadu', 'krishnagiri');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn25', 'tamil_nadu', 'thiruvannamalai');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn28', 'tamil_nadu', 'namakal');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn29', 'tamil_nadu', 'dharmapuri');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn30', 'tamil_nadu', 'selam');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn31', 'tamil_nadu', 'cuddalore');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn32', 'tamil_nadu', 'villupuram');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn33', 'tamil_nadu', 'erode');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn37', 'tamil_nadu', 'coimbatore');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn39', 'tamil_nadu', 'tiruppur');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn40', 'tamil_nadu', 'mettupalayam');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn41', 'tamil_nadu', 'pollachi');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn43', 'tamil_nadu', 'ooty');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn45', 'tamil_nadu', 'tiruchirapalli');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn46', 'tamil_nadu', 'perambalur');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn49', 'tamil_nadu', 'thanjavur');
INSERT INTO location (zone_id, state_name, district_name)
VALUES ('tn50', 'tamil_nadu', 'tiruvaur');
----------------------------------------------------------------------------------------------WAREHOUSE TABLE--------------------------------------------------
CREATE TABLE WAREHOUSE
(
  PREFIX VARCHAR(2) GENERATED ALWAYS AS ('W'),
  W_ID NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 101,
  LOCATION VARCHAR(20) NOT NULL,
  ZONE_ID VARCHAR(4) NOT NULL,
  PRIMARY KEY (W_ID),
  CONSTRAINT warehouse_zone_id_fk FOREIGN KEY (ZONE_ID) REFERENCES LOCATION(ZONE_ID)
);

--INSERT INTO warehouse (location, zone_id) VALUES ('Thanjavur','tn49');
SELECT CONCAT(prefix,w_id)as warehouse_id, location, zone_id FROM warehouse;

select CONCAT(prefix,w_id)as warehouse_id,location, zone_id from warehouse;
select CONCAT(prefix,w_id)as warehouse_id,location, zone_id from warehouse;

commit;

--DROP TABLE warehouse;
-----------------------------------------------------------------------------------------------ACCOUNT TABLE-------------------------------------------------------
CREATE TABLE ACCOUNT
(
  ACCOUNT_NO NUMBER(20) NOT NULL,
  A_HOLDER_NAME VARCHAR(30) NOT NULL,
  BALANCE FLOAT NOT NULL,
  PRIMARY KEY (ACCOUNT_NO)
);

SELECT account_no,a_holder_name,balance FROM account;

UPDATE  account set balance=99999999999 WHERE account_no=1227101051526;

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1227101051526, 'admin',100000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1227101051527, 'seetha',25000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1227101051528, 'ram',30000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1227101051529, 'rajesh',30000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1227101051530, 'pasupathi',30000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1227101051531, 'kaaviya',30000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1227101051532, 'kaniska',20000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1227101051533, 'nantha',20000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1227101051534, 'mari',20000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1227101051535, 'akila',50000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1227101051536, 'nithya',50000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1127101051526, 'pravin',10000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1127101051527, 'karthik',100000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1027101051521, 'sutharsan',100000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1027101051522, 'nithin',100000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1026101051521, 'Karur textiles',2100000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1026101051522, 'Sarathas',5100000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1026101051523, 'kavin',100000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1026101051524, 'barath',100000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1026101051525, 'raja',100000);
--consumer 1
INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1326101051521, 'selvam',10000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1326101051522, 'ravi',10000);

INSERT INTO account (account_no, a_holder_name, balance)
VALUES (1326101051523, 'hari',10000);

update account set balance=1545000 where account_no=1227101051526;

SELECT
    *
FROM account;

commit;
select balance from account where account_no=1227101051526;
--TRUNCATE TABLE account;
----------------------------------------------------------------------------------------------------FUND TABLE--------------------------------------------------

CREATE TABLE fund(
prefix VARCHAR(2) GENERATED ALWAYS AS ('F') NOT NULL,
f_id NUMBER(5) NOT NULL,
fund_amount FLOAT NOT NULL,
donor_account_no NUMBER(20) NOT NULL,
donation_date TIMESTAMP NOT NULL,
  PRIMARY KEY (f_id),
  CONSTRAINT donor_account_no_fk FOREIGN KEY (donor_account_no) REFERENCES ACCOUNT(ACCOUNT_NO)
);

CREATE SEQUENCE f_id_seq START WITH 101 INCREMENT BY 1;

--DROP SEQUENCE f_id_seq;
commit;
SELECT * FROM fund;
--fund sum query
SELECT donor_account_no,sum(fund_amount) as total_fund from fund group by donor_account_no; 

SELECT CONCAT(prefix,f_id) AS fund_id, fund_amount, donor_account_no, donation_date FROM fund;

select sum(fund_amount) from fund;

--INSERT INTO fund(f_id,fund_amount,donor_account_no,donation_date)VALUES(f_id_seq.nextval,1000,1227101051529,LOCALTIMESTAMP);

--UPDATE  fund SET fund_amount=150 WHERE f_id=102;
--DROP TABLE fund;



--------------------------------------------------------------------------------------------------CONSUMER TABLE------------------------------------------------------
CREATE TABLE CONSUMER
(
  PREFIX VARCHAR(2) GENERATED ALWAYS AS ('C'),
  C_ID NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 101,
  CONSUMER_NAME VARCHAR(30) NOT NULL,
  PHONE_NO NUMBER(10) NOT NULL,
  AADHAR_NO NUMBER(12) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  ZONE_ID VARCHAR(4) NOT NULL,
  ACCOUNT_NO NUMBER(20) NOT NULL,
  PRIMARY KEY (C_ID),
  CONSTRAINT consumer_zone_id_fk FOREIGN KEY (ZONE_ID) REFERENCES LOCATION(ZONE_ID),
  CONSTRAINT consumer_account_no_fk FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_NO),
  UNIQUE (PHONE_NO),
  UNIQUE (AADHAR_NO)
);

SELECT CONCAT(prefix,c_id) AS consumer_id, consumer_name,phone_no,aadhar_no,address,zone_id,account_no FROM consumer;
select account_no from consumer where  CONCAT(prefix,c_id)='C123';
select account_no from consumer where CONCAT(prefix,c_id)='C101';
update consumer set c_id = 101 where consumer_name='janu';
--truncate table consumer;
--DROP TABLE consumer;
commit;
--------------------------------------------------------------------------------------------------Distributor table-------------------------------------------
CREATE TABLE DISTRIBUTOR
(
  PREFIX VARCHAR(2) GENERATED ALWAYS AS ('E'),
  S_ID NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 101,
  STAFF_NAME VARCHAR(20) NOT NULL,
  PHONE_NO NUMBER(10) NOT NULL,
  AADHAR_NO NUMBER(12) NOT NULL,
  MAIL_ID VARCHAR(50) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  ZONE_ID VARCHAR(4) NOT NULL,
  ACCOUNT_NO NUMBER(20) NOT NULL,
  PRIMARY KEY (S_ID),
  CONSTRAINT distributor_zone_id_fk FOREIGN KEY (ZONE_ID) REFERENCES LOCATION(ZONE_ID),
  CONSTRAINT distributor_account_no_fk FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_NO),
  UNIQUE (PHONE_NO),
  UNIQUE (AADHAR_NO)

);

SELECT
    *
FROM distributor;

select count(staff_name) from distributor;
select concat(prefix,s_id) as staff_id,zone_id from distributor;
SELECT CONCAT(prefix,s_id) as staff_id, password FROM distributor;

SELECT CONCAT(prefix,s_id) as staff_id, staff_name, phone_no, aadhar_no, mail_id, address, password, zone_id, account_no FROM distributor ;

--INSERT INTO distributor (staff_name, phone_no, aadhar_no, mail_id, address, password, zone_id, account_no) VALUES ('sutharsan',9691173561,956687486591,'sutharsan@gamil.com','trichy','sutharsan@123','tn45',1027101051521);

--Drop table distributor;
------------------------------------------------------------------------------------------------------Seller table--------------------------------------------
CREATE TABLE SELLER
(
  SELLER_ID VARCHAR(4) NOT NULL,
  SELLER_NAME VARCHAR(20) NOT NULL,
  PHONE NUMBER(10) NOT NULL,
  AADHAR_NO NUMBER(12) NOT NULL,
  PAN VARCHAR(11) NOT NULL,
  SHOP_NAME VARCHAR(30) NOT NULL,
  GST_NO VARCHAR(20) NOT NULL,
  MAIL_ID VARCHAR(30) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  ZONE_ID VARCHAR(4) NOT NULL,
  ACCOUNT_NO NUMBER(20) NOT NULL,
  PRIMARY KEY (SELLER_ID),
  CONSTRAINT seller_zone_id_fk FOREIGN KEY (ZONE_ID) REFERENCES LOCATION(ZONE_ID),
  CONSTRAINT seller_account_no_fk FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_NO),
  UNIQUE (PHONE),
  UNIQUE (AADHAR_NO),
  UNIQUE (PAN),
  UNIQUE (GST_NO),
  UNIQUE (MAIL_ID)
);

SELECT seller_id, seller_name, phone, aadhar_no, pan, shop_name, gst_no, mail_id, address, zone_id, account_no FROM seller;


INSERT INTO seller (seller_id, seller_name, phone, aadhar_no, pan, shop_name, gst_no, mail_id, address, zone_id, account_no)
VALUES('S101','saravanan',7373941735,976687486591,'GWKPM139D','KARUR TEXTILES','33AABCU9603R1ZU', 'saravanan@gmail.com', 'karur','tn47',1026101051521);


INSERT INTO seller (seller_id, seller_name, phone, aadhar_no, pan, shop_name, gst_no, mail_id, address, zone_id, account_no)
VALUES('S102','rajasekar',7373941736,976687486592,'GWKPM131D','Sarathas cottons','33AABCU9613R1ZU', 'rajasekar@gmail.com', 'trichy','tn45',1026101051522);



---------------------------------------------------------------------------------------------STOCK TBALE---------------------------------------
CREATE TABLE STOCK
(
  PREFIX VARCHAR(2) GENERATED ALWAYS AS ('S'),
  S_ID NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 101,
  STOCK_NAME VARCHAR(20) NOT NULL,
  QUANTITY NUMBER(10) NOT NULL,
  STAFF_ID VARCHAR(4) NOT NULL,
  WAREHOUSE_ID VARCHAR(4) NOT NULL,
  PRIMARY KEY (S_ID)
 
  --CONSTRAINT stock_warehouse_id_fk FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(W_ID)
);
--TRUNCATE TABLE stock;
--INSERT INTO stock(stock_name, quantity, staff_id, warehouse_id ) VALUES ('BISCUIT',6000,'E101','W101');
SELECT CONCAT (prefix,s_id) as stock_id, stock_name, quantity, staff_id,warehouse_id FROM stock; where warehouse_id='W101';
--update stock set quantity=quantity-2 where warehouse_id='W101' and CONCAT (prefix,s_id)='S102';
SELECT
    *
FROM stock;
--DROP TABLE stock;
-------------------------------------------------------------------------------------------------------Donator table---------------------------------------------
CREATE TABLE DONATOR
(
  PREFIX VARCHAR(2) GENERATED ALWAYS AS ('D'),
  D_ID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 101,
  DONOR_NAME VARCHAR(20) NOT NULL,
  PHONE_NO NUMBER(10) NOT NULL,
  AADHAR_NO NUMBER(12) NOT NULL,
  MAIL_ID VARCHAR(30) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  ZONE_ID VARCHAR(4) NOT NULL,
  ACCOUNT_NO NUMERIC(20) NOT NULL,
  CONSTRAINT donator_zone_id_fk FOREIGN KEY (ZONE_ID) REFERENCES LOCATION(ZONE_ID),
  CONSTRAINT donator_account_no_fk FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_NO),
  UNIQUE (PHONE_NO),
  UNIQUE (AADHAR_NO),
  UNIQUE (MAIL_ID)
);

--CREATE SEQUENCE donor_seq START WITH 101 INCREMENT BY 1; 

--DROP SEQUENCE donor_seq;

SELECT
    *
FROM donator;

select count(donor_name) from donator;
--want to alter this below query to select donation column from fund table with this table
SELECT
    concat (prefix,d_id) as donor_id,donor_name,phone_no,aadhar_no,mail_id,address,password,zone_id,account_no
FROM donator;

SELECT
    concat (prefix,d_id) as donor_id,donor_name,phone_no,aadhar_no,mail_id,address,password,zone_id,account_no,(SELECT donor_account_no,sum(fund_amount) as total_fund from fund group by donor_account_no) as donation  
FROM donator;

--DROP TABLE donator;

commit;
-------------------------------------------------------------------------------------------------------Management table-----------------------------------
CREATE TABLE MANAGEMENT
(
  PREFIX VARCHAR(2) GENERATED ALWAYS AS('M'),
  M_ID NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 101,
  MANAGER_NAME VARCHAR(20) NOT NULL,
  PHONE_NO NUMBER(10) NOT NULL,
  AADHAR_NO NUMBER(12) NOT NULL,
  MAIL_ID VARCHAR(30) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  ZONE_ID VARCHAR(4) NOT NULL,
  ACCOUNT_NO NUMBER(20) NOT NULL,
  PRIMARY KEY (M_ID),
  CONSTRAINT management_zone_id_fk FOREIGN KEY (ZONE_ID) REFERENCES LOCATION(ZONE_ID),
  CONSTRAINT management_account_no_fk FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_NO),
  UNIQUE (PHONE_NO),
  UNIQUE (MAIL_ID),
  UNIQUE (AADHAR_NO)
);

select count(manager_name) from management;
--INSERT INTO management(manager_name, phone_no, aadhar_no, password,mail_id, address, zone_id, account_no) VALUES('pravin',8270870397,966687486591,'pravin@123','pravin@gmail.com','chennai','tn01',1127101051526);
select zone_id from management where concat(prefix,m_id)='M102';
select concat(prefix,m_id) as manager_id from management where phone_no=8270870397;
SELECT concat(prefix,m_id) as manager_id,manager_name, phone_no, aadhar_no,MAIL_ID, password, address, zone_id, account_no FROM management;
--DROP TABLE management;
--TRUNCATE TABLE management;
commit;
-------------------------------------------------------------------------------------------------------Admin table-------------------------------------
CREATE TABLE ADMIN
(
  ADMIN_ID VARCHAR(4) NOT NULL,
  ADMIN_NAME VARCHAR(20) NOT NULL,
  PHONE_NO NUMBER(10) NOT NULL,
  PAN_NO VARCHAR(11) NOT NULL,
  AADHAR_NO NUMBER(12) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  ZONE_ID VARCHAR(4) NOT NULL,
  ACCOUNT_NO NUMBER(20) NOT NULL,
  PRIMARY KEY (ADMIN_ID),
  CONSTRAINT admin_zone_id_fk FOREIGN KEY (ZONE_ID) REFERENCES LOCATION(ZONE_ID),
  CONSTRAINT admin_account_no_fk FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_NO),
  UNIQUE (PHONE_NO),
  UNIQUE (PAN_NO),
  UNIQUE (AADHAR_NO)
);

SELECT
    *
FROM admin;

--UPDATE admin SET admin_name='pravinkumar' WHERE account_no=1227101051526;

--INSERT INTO admin(admin_id, admin_name, phone_no, pan_no, aadhar_no, address, password, zone_id, account_no) 
--VALUES ('a001', 'admin', 9791173564, 'GWKPM138D', 979687486591, 'no.6, north street, pasupathipalayam, karur-639004', 'admin123','tn47', 1227101051526); 

------------------------------------------------------------------------------------------------------Transaction table-----------------------------------
CREATE TABLE TRANSACTION
(
  TRANSACTION_NO NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100001,
  TRANSACTION_DATE TIMESTAMP NOT NULL,
  ACCOUNT_NO NUMBER(20) NOT NULL,
  TRANSACTION_TYPE VARCHAR(10) NOT NULL,
  AMOUNT FLOAT NOT NULL,
  DESCRIPTION VARCHAR(50) NOT NULL,
  PRIMARY KEY (TRANSACTION_NO),
  CONSTRAINT transaction_account_no_fk FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_NO)
);

SELECT TRANSACTION_NO,transaction_date, account_no, transaction_type, amount, description FROM transaction;

--INSERT INTO transaction (transaction_date, account_no, transaction_type, amount, description) VALUES (LOCALTIMESTAMP, 1227101051526, 'credit',2400,'corona welfare fund');
--DROP TABLE transaction;
commit;
--------------------------------------------------------------------------------------------------------Donation table----------------------------------------------
CREATE TABLE DONATION
(
  PREFIX VARCHAR(2) GENERATED ALWAYS AS ('H'),
  H_ID NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 101,
  STAFF_ID VARCHAR(4) NOT NULL,
  CONSUMER_ID VARCHAR(4) NOT NULL,
  STOCK_ID VARCHAR(50),
  QUANTITY NUMBER(6),
  FUND_AMOUNT FLOAT ,
  DESCRIPTION VARCHAR(500) NOT NULL,
  DONATION_DATE TIMESTAMP NOT NULL,
  APPROVED_BY VARCHAR(4),
  APPROVAL_STATUS VARCHAR(20),
  ZONE_ID VARCHAR(4),
  CONSTRAINT donation_zone_id_fk FOREIGN KEY (ZONE_ID) REFERENCES LOCATION(ZONE_ID),
  PRIMARY KEY (H_ID)
  
);

--INSERT INTO donation (staff_id,consumer_id,stock_id,quantity,fund_amount,description,donation_date,approval_status,zone_id) 
--VALUES('E121','C101','S101 S102 S103',2,250,'corona welfare fund',LOCALTIMESTAMP,'Pending','tn47');

SELECT CONCAT(prefix,h_id) as donation_id, staff_id,consumer_id,stock_id,quantity,fund_amount,description,donation_date,approved_by,approval_status,zone_id FROM donation; where zone_id='tn47' and approval_status='Pending';
--UPDATE donation SET approved_by='M101' , approval_status='approved' where approval_status='PENDING';
--SELECT CONCAT(prefix,h_id) as donation_id FROM donation where consumer_id='C101';
--DROP TABLE donation;
select count(consumer_id) as total_people from donation where zone_id='tn47' and approval_status='Approved';
--truncate table donation;
select distinct extract(year from donation_date)as donation_year,(select distinct zone_id ) as zone_id from donation where zone_id='tn45';
select consumer_id from donation where CONCAT(prefix,h_id)='H193';
select sum(fund_amount) from donation where zone_id='tn47';
select count(consumer_id) as total_people from donation where zone_id='tn47';

select distinct zone_id from donation;
commit;





--------------------------------------------------------------------------------------------------DONATION HISTORY TABLE-----------------------------------------
CREATE TABLE donation_history (
prefix VARCHAR(2) GENERATED ALWAYS AS ('H'),
h_id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 101,
zone_id VARCHAR(5),
donation_year TIMESTAMP,
no_of_civilians NUMBER(6),
donation_cause VARCHAR(500),
donation_expenses FLOAT,
UNIQUE (h_id),
CONSTRAINT donation_history_zone_id_fk FOREIGN KEY (zone_id) REFERENCES location(zone_id)
);
--delete donation_history where concat(prefix,h_id)='H102';
--insert into donation_history (zone_id,donation_year,no_of_civilians,donation_cause,donation_expenses) values (null,null,null,null,null);
--insert into donation_history (zone_id,donation_year,no_of_civilians,donation_cause,donation_expenses) values ('tn45',localtimestamp,1200,'flood',250000);
select concat(prefix,h_id) as history_id,zone_id,extract(year from donation_year)as donation_year,no_of_civilians,donation_cause,donation_expenses from donation_history;
--TRUNCATE TABLE donation_history;
select sum(donation_expenses) from donation_history; where zone_id='tn47';
select sum(no_of_civilians) from donation_history;
select no_of_civilians from donation_history where zone_id='tn47';
select distinct extract(year from donation_year)as donation_year,zone_id from donation_history where extract(year from donation_year)=2023 and zone_id='tn47';
--update donation_history set donation_cause= 'Welfare Help' where zone_id='tn47';
--update donation_history set no_of_civilians=no_of_civilians+1 , donation_expenses=donation_expenses+10 where zone_id='tn45';

--drop table donation_history;

--------------------
commit;

select count('fund_amount') from donation where zone_id='tn47';

